version: '2'

volumes:
    mariadb:
    web-certs:

networks:
    nextcloud:

services:
    mysql:
        image: mariadb
        restart: always
        # https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb-large-prefix --innodb-file-per-table --innodb-file-format=barracuda --skip-innodb-read-only-compressed
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        networks:
            - nextcloud

    # DB proxy: watch docker logs to see all sql queries
    # `docker-compose logs -f db`
    db:
        build: ./docker-mysql-proxy
        restart: always
        volumes:
            - ./docker-mysql-proxy/log.lua:/opt/mysql-proxy/conf/log.lua:ro
            - ./docker-mysql-proxy/main.lua:/opt/mysql-proxy/conf/main.lua:ro
        environment:
            PROXY_DB_PORT: 3306
            REMOTE_DB_HOST: mysql
            REMOTE_DB_PORT: 3306
            LUA_SCRIPT: "/opt/mysql-proxy/conf/main.lua"
            LOG_FILE: "/tmp/mysql.log"
        depends_on:
            - mysql
        networks:
            - nextcloud

    php:
        image: skjnldsv/nextcloud-dev
        volumes:
            - ./server:/var/www/nextcloud
            - ./data:/var/www/nextcloud/data
            - ./apps2:/var/www/nextcloud/apps2
            # COMMENT IF YOU WANT FULL CONTROL ON THE NEXTCLOUD INITIAL SETUP
            - ./config/autoconfig.php:/var/www/nextcloud/config/autoconfig.php:ro
            - ./config/debug.config.php:/var/www/nextcloud/config/debug.config.php:ro
            # COMMENT TO DISABLE REDIS
            - ./config/redis.config.php:/var/www/nextcloud/config/redis.config.php:ro
            # UNCOMMENT TO ENABLE SMTP
            # - ./config/smtp.config.php:/var/www/nextcloud/config/smtp.config.php:ro
            - ./config/apps.config.php:/var/www/nextcloud/config/apps.config.php:ro
        restart: always
        environment:
            # use mysql instead of db if you disabled the db proxy
            - MYSQL_HOST=db
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            # comment if redis is disabled
            - REDIS_HOST=redis
            - PHP_IDE_CONFIG='serverName=cli'
            - NEXTCLOUD_DATA_DIR=/var/www/nextcloud/data
            # UNCOMMENT TO ENABLE XDEBUG 
            # host.docker.internal is initiated on the container on each start
            # and bound to the host ip
            - XDEBUG_CONFIG=remote_host=host.docker.internal remote_autostart=On remote_enable=On idekey=XDEBUG remote_log=/tmp/xdebug.log remote_port=9999
            - PHP_XDEBUG_ENABLED=1
            - PHP_XDEBUG_IDE_KEY=XDEBUG
        depends_on:
            # use mysql instead of db if you disabled the db proxy
            - db
            # comment if redis is disabled
            - redis
        networks:
            - nextcloud

    web:
        image: nginx
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./server:/var/www/nextcloud
            - ./apps2:/var/www/nextcloud/apps2
            - ./nextcloud.conf:/etc/nginx/conf.d/default.conf:ro
            - web-certs:/etc/nginx/certs:ro
        restart: always
        networks:
            - nextcloud
        depends_on:
            - php

    omgwtfssl:
        image: paulczar/omgwtfssl
        volumes:
            - web-certs:/certs
        environment:
            # CHANGE IT TO YOU DOMAIN NAME
            - SSL_SUBJECT=dev.domain.com
        networks:
            - nextcloud

    # UNCOMMENT TO ENABLE PHPMYADMIN
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin:latest
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=rootpassword
    #         - MYSQL_PASSWORD=password
    #         - MYSQL_DATABASE=nextcloud
    #         - MYSQL_USER=nextcloud
    #         # use mysql instead of db if you disabled the db proxy
    #         - PMA_HOST=db
    #     restart: always
    #     networks:
    #         - nextcloud
    #     depends_on:
    #         # use mysql instead of db if you disabled the db proxy
    #         - db
    
    # UNCOMMENT TO ENABLE SMTP
    # smtp:
    #     image: namshi/smtp
    #     restart: always
    #     networks:
    #         - nextcloud

    # COMMENT TO DISABLE REDIS
    redis:
        image: redis:latest
        restart: always
        networks:
            - nextcloud
